CREATE TABLE APIARY (
  ID            SERIAL NOT NULL PRIMARY KEY,
  LOCALIZATION  varchar(255),
  INFORMATION   varchar(255));
INSERT INTO APIARY (LOCALIZATION, INFORMATION) VALUES ('Krakow', 'Some interesting apiary');
INSERT INTO APIARY (INFORMATION) VALUES ('This one is only for information');
INSERT INTO APIARY (LOCALIZATION) VALUES ('Lubzina');