subgraphs:
  accounts:
    routing_url: http://localhost:8080
    schema:
      subgraph_url: http://localhost:8080
  apiary:
    routing_url: http://localhost:8081
    schema:
      subgraph_url: http://localhost:8081