subgraphs:
  account:
    routing_url: http://localhost:8080
    schema:
      subgraph_url: http://localhost:8080
  apiary:
    routing_url: http://localhost:8081
    schema:
      subgraph_url: http://localhost:8081
  event:
    routing_url: http://localhost:8082
    schema:
      subgraph_url: http://localhost:8082
  account_apiary:
    routing_url: http://localhost:8083
    schema:
      subgraph_url: http://localhost:8083